# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: wombat 3.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "wombat".freeze
  s.version = "3.2.0".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Felipe Lima".freeze]
  s.date = "1980-01-02"
  s.description = "Generic Web crawler with a DSL that parses structured data from web pages".freeze
  s.email = "felipe.lima@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".github/dependabot.yml",
    ".github/workflows/ci.yml",
    ".rspec",
    ".ruby-version",
    "CHANGELOG.md",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "examples/hashes.rb",
    "examples/iterator.rb",
    "examples/list.rb",
    "examples/no_class.rb",
    "examples/xml.rb",
    "fixtures/vcr_cassettes/basic_crawler_page.yml",
    "fixtures/vcr_cassettes/broken_selector.yml",
    "fixtures/vcr_cassettes/error_page.yml",
    "fixtures/vcr_cassettes/follow_links.yml",
    "fixtures/vcr_cassettes/follow_links_v2.yml",
    "fixtures/vcr_cassettes/follow_relative_links.yml",
    "fixtures/vcr_cassettes/for_each_page.yml",
    "fixtures/vcr_cassettes/headers_selector.yml",
    "fixtures/vcr_cassettes/make_post_request.yml",
    "fixtures/vcr_cassettes/xml_with_namespace.yml",
    "lib/wombat.rb",
    "lib/wombat/crawler.rb",
    "lib/wombat/dsl/follower.rb",
    "lib/wombat/dsl/headers.rb",
    "lib/wombat/dsl/iterator.rb",
    "lib/wombat/dsl/metadata.rb",
    "lib/wombat/dsl/property.rb",
    "lib/wombat/dsl/property_group.rb",
    "lib/wombat/processing/node_selector.rb",
    "lib/wombat/processing/parser.rb",
    "lib/wombat/property/locators/base.rb",
    "lib/wombat/property/locators/factory.rb",
    "lib/wombat/property/locators/follow.rb",
    "lib/wombat/property/locators/headers.rb",
    "lib/wombat/property/locators/html.rb",
    "lib/wombat/property/locators/iterator.rb",
    "lib/wombat/property/locators/list.rb",
    "lib/wombat/property/locators/property_group.rb",
    "lib/wombat/property/locators/text.rb",
    "spec/crawler_spec.rb",
    "spec/dsl/property_spec.rb",
    "spec/helpers/sample_crawler.rb",
    "spec/integration/crawler_inheritance_spec.rb",
    "spec/integration/follow_relative_links_spec.rb",
    "spec/integration/integration_spec.rb",
    "spec/processing/parser_spec.rb",
    "spec/property/locators/factory_spec.rb",
    "spec/property/locators/follow_spec.rb",
    "spec/property/locators/headers_spec.rb",
    "spec/property/locators/html_spec.rb",
    "spec/property/locators/iterator_spec.rb",
    "spec/property/locators/list_spec.rb",
    "spec/property/locators/text_spec.rb",
    "spec/sample_crawler_spec.rb",
    "spec/spec_helper.rb",
    "spec/wombat_spec.rb",
    "wombat.gemspec"
  ]
  s.homepage = "http://felipecsl.github.com/wombat".freeze
  s.licenses = ["MIT".freeze]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9".freeze)
  s.rubygems_version = "3.6.9".freeze
  s.summary = "Ruby DSL to scrape web pages".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<activesupport>.freeze, [">= 0".freeze])
  s.add_runtime_dependency(%q<mechanize>.freeze, ["~> 2.14.0".freeze])
  s.add_runtime_dependency(%q<rest-client>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<bundler>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<coveralls>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<juwelier>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<rake>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<rspec>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<vcr>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<webmock>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<yard>.freeze, [">= 0".freeze])
end

